/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mini.project;

public class App {
  public String getGreeting() {
    return "HI HI";
  }

  public static void main(String[] args) {
    int a = 100;
    if(a >50) {
      System.out.println("크다!");
    }

    System.out.println("오호라!!!!!!");
    System.out.println("졸리고 배고프네요....따흑쒸");
    System.out.println("유부초밥");
  }
}
