/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mini.project;

public class App {
  public String getGreeting() {
    return "Hello world.하핳";
  }

  public static void main(String[] args) {
    System.out.println("오호라!!!!!!");
  }
}
